#!/usr/bin/env python
# -*- coding: UTF-8 -*-

import re
import cgi
import subprocess

import sys
sys.stderr = sys.stdout

print 'Content-Type: text/plain;charset=utf-8'
print ''

def backupConfig():
	file1 = open('/etc/config/wireless', 'r') 
	file2 = open('/etc/config/wireless.bk', 'w')
	file2.write(file1.read())
	file1.close()
	file2.close()
	

def readConfig():
	file = open('/etc/config/wireless', 'r') 
	data = file.read()
	file.close()
	return data

def writeConfig(data):
	file = open('/etc/config/wireless', 'w')
	file.write(data)
	file.close()

def restartWifi():
	out = subprocess.Popen(['wifi'], stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
	stdout,stderr = out.communicate()
	return stdout

def setValue(config, iface, option, value):
	config = config.split('\n')

	iface_section = False
	for i,line in enumerate(config):
		iface_match = re.match(r'config wifi-iface \'(.*)\'', line)
		if iface_match:
			if  iface_match.group(1) == iface:
				iface_section = True
			else:
				iface_section = False

		if iface_section == True:
			option_match = re.match(r'.*option ' + option + r' \'(.*)\'', line)
			if option_match:
				config[i] = line.replace(option_match.group(1), value)
				break
	return '\n'.join(config)

backupConfig()

config = readConfig()

form = cgi.FieldStorage()
for val in {'ssid', 'key'}:
	if val in form:


		config = setValue(config, 'ap', val, form.getvalue(val))

writeConfig(config)

restartWifi()

print 'OK'
